### PR TITLE
Fix timer metrics in DefaultOutput

### LINKED ISSUE #26: Timers use infinite reservoir
https://github.com/teragrep/aer_01/blob/79b1032ce0e8f3fbb7874cf3e30e6729eb2be77a/src/main/java/com/teragrep/aer_01/DefaultOutput.java#L100-L101

Should use a limited sample pool.

See example in https://github.com/teragrep/cfe_35/blob/main/src/main/java/com/teragrep/cfe_35/router/MessageParser.java#L95-L98

Please create documentation how to use the metrics library based on the pr https://github.com/teragrep/aer_01/commit/79b1032ce0e8f3fbb7874cf3e30e6729eb2be77a

### PR DESCRIPTION
**Pull request by 51-code**
Fixes #26. The timers were not limited on how many records they can hold. This introduced overflow problems.

PR includes:
- Using `SlidingWindowReservoir` in Timers.
- Fixing the `connectLatency` timer. It was also taking count on the latency when the server threw an Exception and this is not wanted behavior.
- Tests for the Timers in DefaultOutput.
- Refactoring of the metric tests in EventContextConsumerTest and moving fake objects to their own folder.

Explanations on a few coding choices:
- The DefaultOutput has code in its constructor. There really is no better alternative. Opened an issue in the relevant library here: [teragrep/rlp_01 #68](https://github.com/teragrep/rlp_01/issues/68)
- Not counting the latency when throwing exceptions requires that the timer is not used with try-with-resources like usual. This means that the close function is not always called, just when the `connect()` call returns a boolean value. This does not matter, because Timer's source code shows that the close doesn't actually close any resources, it just calls stop() on the timer which does not reset it, it just updates the value. The actual reset is done by creating a new Timer.context instance as in the code now.

### CODE REVIEW

File: src/test/java/com/teragrep/aer_01/EventContextConsumerTest.java [hunk 1]
```diff
@@ -52,96 +52,99 @@
...
-                length = length + eventContext.getEventData().getBody().length;
-                eventContextConsumer.accept(eventContext);
+    public void testDepthBytesMetric() {
+        EventContext eventContext = eventContextFactory.create();
+        eventContextConsumer.accept(eventContext);
+
+        long depth1 = 0L;
+        final double records = 10;
+        for (int i = 1; i < records; i++) { // records - 1 loops
+            if (i == 5) { // 5 records per partition
```
Comment (eemhu) [inline src/test/java/com/teragrep/aer_01/EventContextConsumerTest.java:117]: is there a reason this was changed from i==4 to i==5?

**Review by eemhu — COMMENTED** [review]
Otherwise, looks good to me, if these test changes are okay. Expected values seem to remain same.

File: src/test/java/com/teragrep/aer_01/EventContextConsumerTest.java (hunk 1 above)
Comment (51-code) [reply src/test/java/com/teragrep/aer_01/EventContextConsumerTest.java:117]: It still checks the fifth eventContext created. This is difficult to see in the GitHub review tool, but the if clause was moved from the end of the loop to the start of the loop. Before it created a new context and then checked the if statement, now it checks the if statement and then creates a new context, so that's why the index was incremented by one in the if statement.

**Comment by 51-code** [comment]
Tried to solve the issue with mutable fakes. They are mutable now because it counts the amount of connections. To solve it, the `connect` function call should return a new instance of the class instead of changing the state. This is not possible with the current code however. I commented on the previous issue I made in RLP-01 that the class should be refactored: [teragrep/rlp_01 #68](https://github.com/teragrep/rlp_01/issues/68)

**Review by eemhu — APPROVED** [review]
This looks good to me, if @kortemik is okay with this solution?

File: src/main/java/com/teragrep/aer_01/DefaultOutput.java [hunk 2]
```diff
@@ -97,17 +105,19 @@ final class DefaultOutput implements Output {
...
     }
 
     private void connect() {
         boolean connected = false;
         while (!connected) {
-            try (final Timer.Context context = connectLatency.time()) {
+            final Timer.Context context = connectLatency.time(); // reset the time (new context)
+            try {
                 connected = this.relpConnection.connect(relpAddress, relpPort);
+                context.close(); // manually close here, so the timer is only updated if no exceptions were thrown
```
Comment (kortemik) [inline src/main/java/com/teragrep/aer_01/DefaultOutput.java:120]: if line 119 connect throws, close is never called and timer is left open, will this cause a problem?

**Review by kortemik — CHANGES_REQUESTED** [review]

File: src/main/java/com/teragrep/aer_01/DefaultOutput.java (hunk 2 above)
Comment (51-code) [reply src/main/java/com/teragrep/aer_01/DefaultOutput.java:120]: Closing the context will always update the timed value as well. So only way not to include these cases where an exception is thrown, would be to not close it.

I looked at the source code of Timer.Context and it just calls the stop() function, which is a way of manually updating the value. It is a bit weird, stop() is documented like this: 

> Updates the timer with the difference between current and start time. Call to this method will not reset the start time. Multiple calls result in multiple updates.

And the close() is documented like this: 

> Equivalent to calling stop().

So to my knowledge it doesn't really matter if close() is called or not, the timer context is always left open.

**Review by kortemik — CHANGES_REQUESTED** [review]

**Review by kortemik — APPROVED** [review]
